export interface Job {
  title: string;
  slug: string;
  type: "FULL_TIME" | "PART_TIME" | "SEASONAL" | "CONTRACT";
  payType: "hourly" | "salary";
  payMin: number;
  payMax: number;
  payCurrency: string;
  payUnit: string;
  shortDesc: string;
  description: string;
  responsibilities: string[];
  qualifications: string[];
  benefits: string[];
  physical: string[];
  schedule: string;
  experience: string;
}

export const jobs: Job[] = [
  {
    title: "Landscaper / Landscape Technician",
    slug: "landscaper",
    type: "FULL_TIME",
    payType: "hourly",
    payMin: 18,
    payMax: 28,
    payCurrency: "USD",
    payUnit: "HOUR",
    shortDesc: "Hands-on landscape installation, planting, grading, and maintenance across NYC properties.",
    description:
      "We are looking for experienced landscapers and landscape technicians to join our field crews. You will perform landscape installations, plantings, hardscape prep, grading, mulching, sod installation, and general site work across residential and commercial properties in all five NYC boroughs, Long Island, and Westchester. This is a physical, outdoor role for someone who takes pride in transforming spaces and isn't afraid of hard work in any season.",
    responsibilities: [
      "Install plants, shrubs, trees, sod, and ground cover per design specifications",
      "Perform grading, soil amendment, and site preparation",
      "Assist with hardscape installations including pavers, retaining walls, and edging",
      "Load and unload materials, operate hand tools and small equipment",
      "Maintain clean and organized job sites",
      "Perform seasonal maintenance including spring cleanups, fall leaf removal, and winter prep",
      "Follow safety protocols and use PPE at all times",
      "Communicate with crew leader on daily tasks and progress",
    ],
    qualifications: [
      "1+ years of hands-on landscaping or related outdoor work experience",
      "Ability to identify common plants, shrubs, and trees",
      "Comfortable operating hand tools, wheelbarrows, and small power equipment",
      "Valid driver's license preferred",
      "Reliable transportation to job sites across NYC metro area",
      "Ability to work outdoors in all weather conditions",
      "Strong work ethic and team-oriented attitude",
      "English proficiency (Spanish bilingual a plus)",
    ],
    benefits: [
      "Competitive hourly pay: $18–$28/hr based on experience",
      "Consistent year-round work (snow removal in winter)",
      "Overtime opportunities during peak season",
      "Paid training and skill development",
      "Opportunity to advance to Crew Leader",
      "Tools and safety equipment provided",
      "Supportive team environment",
    ],
    physical: [
      "Ability to lift 50+ lbs regularly",
      "Standing, bending, kneeling for extended periods",
      "Working outdoors in heat, cold, rain, and snow",
      "Climbing ladders and working on uneven terrain",
    ],
    schedule: "Monday–Friday, 7:00 AM – 4:00 PM. Occasional Saturdays during peak season.",
    experience: "1+ years landscaping experience preferred. Will train the right candidate.",
  },
  {
    title: "Landscape Designer",
    slug: "landscape-designer",
    type: "FULL_TIME",
    payType: "salary",
    payMin: 55000,
    payMax: 85000,
    payCurrency: "USD",
    payUnit: "YEAR",
    shortDesc: "Create custom landscape designs for NYC residential and commercial properties using 3D modeling and CAD.",
    description:
      "We are hiring a Landscape Designer to join our design team. You will create custom landscape plans for residential and commercial properties across NYC, from Brooklyn brownstone backyards to Manhattan rooftop gardens to Westchester estates. This role combines creativity with practical knowledge of NYC growing conditions, regulations, and site constraints. You will work directly with clients from concept through installation, collaborating closely with our field crews to ensure designs are executed to specification.",
    responsibilities: [
      "Conduct on-site consultations and property surveys",
      "Create detailed landscape designs using CAD/SketchUp/3D rendering software",
      "Select plants appropriate for NYC Zone 7a/7b conditions",
      "Develop planting plans, hardscape layouts, irrigation plans, and lighting designs",
      "Prepare material lists, cost estimates, and project timelines",
      "Present designs to clients and incorporate feedback",
      "Coordinate with installation crews during build phase",
      "Stay current on NYC DOB regulations, permits, and green building codes",
      "Manage multiple concurrent design projects",
    ],
    qualifications: [
      "Bachelor's degree in Landscape Architecture, Horticulture, or related field",
      "3+ years of landscape design experience, preferably in urban environments",
      "Proficiency in AutoCAD, SketchUp, and/or Lumion for 3D renderings",
      "Strong knowledge of plants suitable for NYC microclimates",
      "Understanding of NYC building codes, DOB permits, and co-op/condo requirements",
      "Experience with rooftop garden design and structural load considerations",
      "Excellent client communication and presentation skills",
      "Portfolio of completed residential and/or commercial projects",
      "Valid driver's license",
    ],
    benefits: [
      "Salary: $55,000–$85,000 based on experience and portfolio",
      "Health insurance contribution",
      "Paid time off and holidays",
      "Professional development budget",
      "Design software licenses provided",
      "Flexible schedule with remote design days",
      "Creative autonomy on projects",
      "Career growth into Lead Designer or Project Manager",
    ],
    physical: [
      "Ability to visit job sites across NYC metro area",
      "Walking, measuring, and surveying outdoor properties",
      "Occasional lifting of survey equipment (under 30 lbs)",
    ],
    schedule: "Monday–Friday, 8:00 AM – 5:00 PM. Flexible remote days for design work.",
    experience: "3+ years landscape design experience. Urban/NYC experience strongly preferred.",
  },
  {
    title: "Irrigation Technician",
    slug: "irrigation-technician",
    type: "FULL_TIME",
    payType: "hourly",
    payMin: 22,
    payMax: 35,
    payCurrency: "USD",
    payUnit: "HOUR",
    shortDesc: "Install, maintain, and repair irrigation systems for residential and commercial landscapes across NYC.",
    description:
      "We are hiring an experienced Irrigation Technician to install, maintain, troubleshoot, and repair drip and spray irrigation systems across our residential and commercial properties. NYC irrigation work includes rooftop systems, backyard zones, commercial property controllers, and smart irrigation technology. You will work with our design team to plan efficient water distribution and with our maintenance team to keep systems running through every season.",
    responsibilities: [
      "Install new drip and spray irrigation systems per design specifications",
      "Program and configure smart irrigation controllers and rain sensors",
      "Perform spring startups, mid-season adjustments, and fall winterizations",
      "Diagnose and repair leaks, broken heads, valve issues, and controller malfunctions",
      "Run trenching and pipe work for new installations",
      "Coordinate with landscape designers on irrigation plans for new projects",
      "Maintain accurate records of system layouts and components",
      "Educate property owners on system operation and seasonal adjustments",
    ],
    qualifications: [
      "2+ years of irrigation installation and repair experience",
      "Knowledge of drip, spray, rotor, and micro-irrigation systems",
      "Experience with smart controllers (Rain Bird, Hunter, Rachio)",
      "Ability to read irrigation design plans and blueprints",
      "Basic electrical knowledge for controller wiring",
      "NYC backflow prevention certification preferred",
      "Valid driver's license and reliable transportation",
      "Ability to work independently and manage daily route",
    ],
    benefits: [
      "Competitive hourly pay: $22–$35/hr based on experience",
      "Year-round work (winterization in fall, maintenance year-round)",
      "Company vehicle for service routes (after 90 days)",
      "Tool allowance",
      "Training on latest smart irrigation technology",
      "Overtime during peak installation season",
      "Path to Lead Irrigation Technician",
    ],
    physical: [
      "Ability to lift 50+ lbs",
      "Trenching, digging, and working in confined spaces",
      "Working outdoors in all weather conditions",
      "Kneeling, bending, and crawling for extended periods",
    ],
    schedule: "Monday–Friday, 7:00 AM – 4:00 PM. Some Saturdays during peak season.",
    experience: "2+ years irrigation experience required.",
  },
  {
    title: "Tree Care Specialist",
    slug: "tree-care-specialist",
    type: "FULL_TIME",
    payType: "hourly",
    payMin: 20,
    payMax: 32,
    payCurrency: "USD",
    payUnit: "HOUR",
    shortDesc: "Prune, maintain, plant, and care for trees and large shrubs across NYC properties.",
    description:
      "We are looking for a Tree Care Specialist to handle pruning, planting, health assessments, and maintenance of trees and large shrubs across our residential and commercial properties. NYC tree work requires knowledge of city regulations (Parks Department permits for street trees), confined-space climbing, and species-specific care in an urban environment. You will work both independently and with our landscape crews.",
    responsibilities: [
      "Prune, shape, and maintain trees and large shrubs per ISA standards",
      "Plant new trees including staking, guying, and root ball preparation",
      "Diagnose tree health issues including disease, pest damage, and structural problems",
      "Apply treatments for common NYC tree diseases and pests",
      "Perform safe removal of dead limbs, storm damage cleanup, and emergency response",
      "Coordinate with NYC Parks Department for street tree work permits",
      "Operate and maintain chainsaws, pole saws, and chippers safely",
      "Document tree health and maintenance records for property managers",
    ],
    qualifications: [
      "2+ years of professional tree care or arborist experience",
      "ISA Certified Arborist preferred (or willingness to pursue certification)",
      "Knowledge of common NYC tree species and their care requirements",
      "Experience with pruning standards (ANSI A300)",
      "Safe operation of chainsaws, pole saws, chippers, and aerial lifts",
      "Understanding of NYC Parks Department regulations for tree work",
      "Valid driver's license (CDL a plus for chip trucks)",
      "Comfort working at heights and in confined urban spaces",
    ],
    benefits: [
      "Competitive hourly pay: $20–$32/hr based on experience and certifications",
      "ISA certification reimbursement",
      "Year-round work",
      "Safety gear and equipment provided",
      "Emergency response premium pay",
      "Career growth to Lead Arborist",
      "Overtime opportunities",
    ],
    physical: [
      "Climbing trees and working at heights up to 60+ feet",
      "Lifting 50+ lbs regularly (limbs, equipment, wood)",
      "Operating heavy equipment (chippers, aerial lifts)",
      "Working in all weather conditions including storms",
    ],
    schedule: "Monday–Friday, 7:00 AM – 4:00 PM. On-call for storm emergencies.",
    experience: "2+ years tree care experience. ISA certification preferred.",
  },
  {
    title: "Snow Removal Crew Member",
    slug: "snow-removal-crew",
    type: "SEASONAL",
    payType: "hourly",
    payMin: 20,
    payMax: 30,
    payCurrency: "USD",
    payUnit: "HOUR",
    shortDesc: "Seasonal snow plowing, shoveling, salting, and ice management for NYC properties.",
    description:
      "We are hiring Snow Removal Crew Members for the winter season (November through March). You will perform snow plowing, hand shoveling, salting, ice management, and walkway clearing for our residential and commercial properties across NYC. This is on-call work — when it snows, you work. We need reliable people who can respond quickly and work through the night when needed.",
    responsibilities: [
      "Plow driveways, parking lots, and access roads using truck-mounted plows",
      "Hand-shovel walkways, stoops, building entrances, and emergency exits",
      "Apply salt and de-icing materials to walkways and parking areas",
      "Clear fire hydrants, ADA ramps, and building access points",
      "Monitor weather conditions and respond to dispatch calls within 1 hour",
      "Maintain and inspect snow removal equipment before and after each event",
      "Document completed work with photos and timestamps",
      "Follow all safety protocols for working in winter conditions",
    ],
    qualifications: [
      "Previous snow removal experience preferred (residential or commercial)",
      "Valid driver's license (CDL preferred for plow trucks)",
      "Ability to operate snow plows, salt spreaders, and snow blowers",
      "Available on-call November through March (including nights and weekends)",
      "Reliable transportation to report to staging area within 1 hour of dispatch",
      "Physical ability to shovel for extended periods in extreme cold",
      "Team-oriented and reliable — no no-shows during storms",
      "NYC area resident preferred for fast response times",
    ],
    benefits: [
      "Competitive hourly pay: $20–$30/hr",
      "Storm premium pay for overnight and extended events",
      "Guaranteed minimum hours per storm event",
      "Equipment and safety gear provided",
      "Priority hiring for spring/summer landscape positions",
      "Tips from residential clients",
    ],
    physical: [
      "Shoveling for 4–12+ hours continuously during storm events",
      "Working in sub-freezing temperatures, wind, and heavy snow",
      "Lifting 50+ lbs (salt bags, equipment)",
      "Operating plows and heavy equipment in low-visibility conditions",
    ],
    schedule: "On-call, November–March. When it snows, you work. Events can last 4–24+ hours.",
    experience: "Previous snow removal experience preferred. Will train motivated candidates.",
  },
  {
    title: "Crew Leader / Foreman",
    slug: "crew-leader",
    type: "FULL_TIME",
    payType: "hourly",
    payMin: 28,
    payMax: 42,
    payCurrency: "USD",
    payUnit: "HOUR",
    shortDesc: "Lead landscape installation and maintenance crews across NYC. Manage daily operations, quality, and safety.",
    description:
      "We are hiring an experienced Crew Leader / Foreman to manage our field crews on landscape installation and maintenance projects across NYC. You will be responsible for daily crew management, job site organization, quality control, client communication, and ensuring projects are completed on time and to specification. This is a leadership role for someone who has been in the field, knows the work inside and out, and can motivate a team to deliver excellence every day.",
    responsibilities: [
      "Lead and manage a crew of 3–6 landscapers on daily assignments",
      "Execute landscape installations per designer specifications",
      "Ensure quality standards on all plantings, hardscape, and maintenance work",
      "Manage job site safety, tool inventory, and material staging",
      "Communicate daily with project managers on progress, issues, and changes",
      "Train and mentor junior crew members",
      "Operate and maintain all landscape equipment (mowers, skid steers, compactors)",
      "Handle on-site client interactions professionally",
      "Complete daily job reports with photos, hours, and material usage",
      "Coordinate material deliveries and subcontractor schedules",
    ],
    qualifications: [
      "4+ years of professional landscaping experience with 2+ in a leadership role",
      "Proven ability to lead, motivate, and manage a field crew",
      "Strong knowledge of landscape installation, hardscaping, and maintenance",
      "Ability to read and execute landscape design plans",
      "Experience operating skid steers, compactors, and commercial mowers",
      "Valid driver's license (CDL preferred)",
      "OSHA 10 or 30 certification preferred",
      "Bilingual English/Spanish strongly preferred",
      "NYC-specific experience (access logistics, permits, co-op/condo coordination)",
    ],
    benefits: [
      "Competitive hourly pay: $28–$42/hr based on experience",
      "Company truck and fuel card",
      "Health insurance contribution",
      "Paid time off",
      "Performance bonuses",
      "Year-round employment (snow operations in winter)",
      "Path to Operations Manager or Project Manager",
      "OSHA certification reimbursement",
    ],
    physical: [
      "Ability to perform all landscape tasks alongside crew when needed",
      "Lifting 50+ lbs regularly",
      "Working outdoors in all weather conditions year-round",
      "Driving crew trucks and towing trailers",
    ],
    schedule: "Monday–Friday, 6:30 AM – 4:30 PM. Saturdays during peak season. On-call for snow.",
    experience: "4+ years landscaping with 2+ years in a leadership/foreman role.",
  },
];

export function findJobBySlug(slug: string): Job | undefined {
  return jobs.find((j) => j.slug === slug);
}

export function getAllJobSlugs(): string[] {
  return jobs.map((j) => j.slug);
}
